### ISSUE TITLE
Can run bms.py

### ISSUE THREAD

**Issue by dAtiuy** [stt/py#1]
This is what I get... when running python bms.py (game files and shit). python bms.py
  File "bms.py", line 98
    print var,pos,sz,fnum
            ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print(var,pos,sz,fnum)?
 This what I get when I use python 2. python2 bms.py
Traceback (most recent call last):
  File "bms.py", line 11, in <module>
    from bmslex import lexer
  File "/data/data/com.termux/files/home/py/pybms/bmslex.py", line 6, in <module>
    import ply.lex as lex
ImportError: No module named ply.lex

**Comment by stt** [comment]
yea it's py2 only, readme lists the only other requirement which is PLY (try `pip2 install ply`).
it should be pretty easy to upgrade for py3 (just runnign through 2to3-tool should fix those prints), but it's likely going to need some love to deal with different bms scripts, don't think I ever tested it with more than couple scripts.

but how'd you even find this? it's been untouched for 6y, feel like I should give you a prize :)
